# ============================================================================
# __APP_NAME__ Deployment YAML 生成配置
# ============================================================================

TEMPLATE_FILE="templates/app/__APP_NAME__.yaml"
OUTPUT_FILE="__APP_NAME__-generated.yaml"
ENABLED="true"
RESOURCE_TYPE="app"

NAMESPACE="${NAMESPACE:-__NAMESPACE__}"
ENVIRONMENT="${ENVIRONMENT:-development}"
ENV="${ENV:-dev}"

# 镜像配置
__APP_NAME_UPPER___IMAGE_REGISTRY="${__APP_NAME_UPPER___IMAGE_REGISTRY:-__REGISTRY__}"
KIND___APP_NAME_UPPER___IMAGE_REGISTRY="__KIND_REGISTRY__"
__APP_NAME_UPPER___IMAGE_PROJECT="${__APP_NAME_UPPER___IMAGE_PROJECT:-__IMAGE_PROJECT__}"
__APP_NAME_UPPER___IMAGE="${__APP_NAME_UPPER___IMAGE:-__APP_NAME__}"
__APP_NAME_UPPER___TAG="${__APP_NAME_UPPER___TAG:-1.0.0}"
IMAGE_PULL_POLICY="${IMAGE_PULL_POLICY:-Always}"
__APP_NAME_UPPER___IMAGE_PULL_SECRET_NAME="${__APP_NAME_UPPER___IMAGE_PULL_SECRET_NAME:-harbor-registry-secret}"

# Secret / ConfigMap 名称
__APP_NAME_UPPER___SECRET_NAME="${__APP_NAME_UPPER___SECRET_NAME:-__APP_NAME__-secret}"
__APP_NAME_UPPER___CONFIGMAP_NAME="${__APP_NAME_UPPER___CONFIGMAP_NAME:-__APP_NAME__-config}"
__APP_NAME_UPPER___OBJECT_STORAGE_CONFIGMAP_NAME="${__APP_NAME_UPPER___OBJECT_STORAGE_CONFIGMAP_NAME:-__OBJECT_STORAGE_CONFIGMAP_NAME__}"
__APP_NAME_UPPER___OBJECT_STORAGE_SECRET_NAME="${__APP_NAME_UPPER___OBJECT_STORAGE_SECRET_NAME:-__OBJECT_STORAGE_SECRET_NAME__}"
__APP_NAME_UPPER___ELASTICSEARCH_CONFIGMAP_NAME="${__APP_NAME_UPPER___ELASTICSEARCH_CONFIGMAP_NAME:-__ELASTICSEARCH_CONFIGMAP_NAME__}"
__APP_NAME_UPPER___ELASTICSEARCH_SECRET_NAME="${__APP_NAME_UPPER___ELASTICSEARCH_SECRET_NAME:-__ELASTICSEARCH_SECRET_NAME__}"
__APP_NAME_UPPER___POSTGRESQL_SECRET_NAME="${__APP_NAME_UPPER___POSTGRESQL_SECRET_NAME:-__POSTGRESQL_SECRET_NAME__}"
__APP_NAME_UPPER___REDIS_SECRET_NAME="${__APP_NAME_UPPER___REDIS_SECRET_NAME:-__REDIS_SECRET_NAME__}"
__APP_NAME_UPPER___MONGODB_SECRET_NAME="${__APP_NAME_UPPER___MONGODB_SECRET_NAME:-__MONGODB_SECRET_NAME__}"

# PVC 配置
PVC_NAME="${PVC_NAME:-__APP_NAME__-pvc}"
PVC_MOUNT_PATH="${PVC_MOUNT_PATH:-/app/data}"
PVC_SUB_PATH="${PVC_SUB_PATH:-}"
